project:
  type: website
  output-dir: docs

website:
  favicon: images/chick.png
  navbar:
    title: false
    logo: images/logos/nunito/creamBG_greenText/logo_nunito_cropped.png
    logo-alt: "The name 'sam csik' written in green text. Above 'csik' is a dark green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - resources.qmd
      - href: posts.qmd
        text: posts
      - href: CV/SCsik_CV.pdf
        text: cv
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
  page-footer: 
    background: light
    left: 
      - "Copyright 2021, Samantha Csik"
    right: 
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Silkscreen
    toc: true


