project:
  type: website
  output-dir: docs

website:
  title: "samantha csik"
  navbar:
    title: samanthacsik
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: home # use 'text' option to update the name as it appears in your navbar
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


