project:
  type: website
  output-dir: docs

website:
  title: "samantha csik"
  navbar:
    title: samanthacsik
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: talks_workshops.qmd
        text: talks & workshops
      - posts.qmd
      - resources.qmd
      - href: CV/SCsik_CV.pdf
        text: cv
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


